<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="13.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hotel.Infrastructure\Hotel.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Booking\Query\" />
  </ItemGroup>

</Project>
